name: Xenial CI

on: [pull_request, push]

jobs:
  build-linux:
    name: "Build - Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-docker.sh 14.04 hosts/linux_x86_64.env targets/aarch64-xenial
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: build/aarch64-xenial/Linux/aarch64-xenial-*-Linux*.tar.gz

  build-windows:
    name: "Build - Windows"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build-docker.sh 18.04 hosts/windows_i686.env targets/aarch64-xenial
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: build/aarch64-xenial/Windows/aarch64-xenial-*-Windows*.zip
  build-macos:
    name: "Build - MacOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install coreutils
        run: brew install coreutils gnu-tar
      - name: Build
        run: ./build.sh hosts/macos_generic.env targets/aarch64-xenial
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: build/aarch64-xenial/Mac/aarch64-xenial-*-Mac*.tar.gz